<a href="https://colab.research.google.com/github/muskanalirizvi/Practice-sklearn/blob/main/OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd

df = pd.read_csv('cars.csv')
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [4]:
df.shape

(8128, 5)

In [27]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [6]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [7]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [8]:
ValueCount = df['brand'].value_counts()
LessFrequencyBrands = ValueCount[ValueCount<100].index
LessFrequencyBrands

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [9]:
df['brand'] = df['brand'].replace(LessFrequencyBrands,'other')

In [10]:
df.tail(20)

        brand  km_driven    fuel                 owner  selling_price
8108    other      20000  Diesel           First Owner        1575000
8109     Ford      24000  Diesel           First Owner         750000
8110   Maruti      12000  Petrol           First Owner         425000
8111   Toyota      50000  Diesel           First Owner         425000
8112     Ford      24000  Diesel           First Owner         746000
8113   Toyota     129000  Diesel           First Owner         425000
8114   Maruti      73000  Petrol           First Owner         200000
8115   Maruti     120000  Petrol           First Owner          40000
8116   Maruti      45000  Petrol           First Owner         340000
8117   Maruti      50000  Diesel           First Owner         625000
8118  Hyundai      25000  Petrol           First Owner         380000
8119   Maruti      80000  Petrol           First Owner         360000
8120  Hyundai     191000  Petrol           First Owner         120000
8121   Maruti      50000  Petrol          Second Owner         260000
8122  Hyundai      80000  Diesel          Second Owner         475000
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop(['selling_price'],axis=1),df['selling_price'] ,test_size=0.3)

In [14]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
ohe = OneHotEncoder(drop = 'first', sparse_output = False)

x_train_encoded = ohe.fit(x_train[['brand', 'fuel', 'owner']])

In [15]:
x_train_encoded = ohe.transform(x_train[['brand', 'fuel', 'owner']])
x_test_encoded = ohe.transform(x_test[['brand', 'fuel', 'owner']])

In [16]:
column_names = ohe.get_feature_names_out(['brand', 'fuel','owner'])

In [17]:
x_train_encode = pd.DataFrame(x_train_encoded, columns = column_names)
x_test_encode = pd.DataFrame(x_test_encoded, columns = column_names)

In [18]:
x_train_encode.head()

,brand_Chevrolet,brand_Ford,brand_Honda,brand_Hyundai,brand_Mahindra,brand_Maruti,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_other,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
x_train_Dataframe = pd.concat([x_train.reset_index(drop=True).drop(['brand', 'fuel', 'owner'], axis=1), x_train_encode], axis=1)
columns_to_encode = ['brand', 'fuel', 'owner']
x_test_Dataframe = pd.concat([x_test.reset_index(drop=True).drop(['brand', 'fuel', 'owner'], axis=1), x_test_encode], axis=1)

In [20]:
x_train_Dataframe

,km_driven,brand_Chevrolet,brand_Ford,brand_Honda,brand_Hyundai,brand_Mahindra,brand_Maruti,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_other,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,7000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,100600,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,140000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,68089,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,80000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5684,82500,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
5685,110000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
5686,64800,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5687,70000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5688,80000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0

In [21]:
x_train_Dataframe.shape

(5689, 20)

In [23]:
x_test_Dataframe.shape

(2439, 20)

In [24]:
5689+2439

8128